readme: README.md
files:
  - name: 第一話.md
    type: content
    path: /home/cedretaber/src/ts/dialogoi-editor/examples/newnovel/本文/第一話.md
    tags:
      - プロローグ
      - 初回
  - name: 第二話.txt
    type: content
    path: /home/cedretaber/src/ts/dialogoi-editor/examples/newnovel/本文/第二話.txt
    tags:
      - 魔法
  - name: 第三話.txt
    type: content
    path: /home/cedretaber/src/ts/dialogoi-editor/examples/newnovel/本文/第三話.txt
