readme: README.md
files:
  - name: world_setting.md
    type: setting
    tags:
      - 世界観
      - 基本設定
    references:
      - contents/02_entrance_ceremony.txt
    hash: ''
    comments: ''
    isUntracked: false
    isMissing: false
  - name: magic_system.md
    type: setting
    tags:
      - 魔法
      - システム
    references:
      - contents/03_first_magic_lesson.txt
    hash: ''
    comments: ''
    isUntracked: false
    isMissing: false
  - name: glossary.md
    type: setting
    glossary: true
    tags:
      - 用語集
    hash: ''
    comments: ''
    isUntracked: false
    isMissing: false
  - name: characters
    type: subdirectory
    isUntracked: false
    isMissing: false
  - name: foreshadowings
    type: subdirectory
    isUntracked: false
    isMissing: false
