readme: README.md
files:
  - name: world_setting.md
    type: setting
    tags: ["世界観", "基本設定"]
    referenced: ["contents/01_prologue.txt", "contents/02_entrance_ceremony.txt"]
  - name: magic_system.md
    type: setting
    tags: ["魔法", "システム"]
    referenced: ["contents/03_first_magic_lesson.txt"]
  - name: glossary.md
    type: setting
    glossary: true
    tags: ["用語集"]
  - name: characters
    type: subdirectory
  - name: foreshadowings
    type: subdirectory