readme: README.md
files:
  - name: tarou.md
    type: setting
    character:
      importance: main
      multiple_characters: false
    tags:
      - 主人公
      - メインキャラクター
    references:
      - contents/01_prologue.txt
      - contents/02_entrance_ceremony.txt
      - contents/03_first_magic_lesson.txt
      - contents/04_new_friendship.txt
    hash: ''
    comments: ''
    isUntracked: false
    isMissing: false
  - name: hanako.md
    type: setting
    character:
      importance: main
      multiple_characters: false
    tags:
      - ヒロイン
      - メインキャラクター
    references:
      - contents/02_entrance_ceremony.txt
      - contents/03_first_magic_lesson.txt
      - contents/04_new_friendship.txt
    hash: ''
    comments: ''
    isUntracked: false
    isMissing: false
  - name: jirou.md
    type: setting
    character:
      importance: sub
      multiple_characters: false
    tags:
      - 親友
      - サブキャラクター
    references:
      - contents/04_new_friendship.txt
    hash: ''
    comments: ''
    isUntracked: false
    isMissing: false
  - name: teachers.md
    type: setting
    character:
      importance: background
      multiple_characters: true
    tags:
      - 教師
      - サブキャラクター
    references:
      - contents/02_entrance_ceremony.txt
      - contents/03_first_magic_lesson.txt
    hash: ''
    comments: ''
    isUntracked: false
    isMissing: false
