readme: README.md
files:
  - name: 主人公.md
    type: setting
    path: /home/cedretaber/src/ts/dialogoi-editor/examples/newnovel/設定/主人公.md
    character:
      importance: main
      multiple_characters: false
  - name: 伏線1.md
    type: setting
    path: /home/cedretaber/src/ts/dialogoi-editor/examples/newnovel/設定/伏線1.md
    foreshadowing:
      start: ''
      goal: ''
