readme: README.md
files:
  - name: contents
    type: subdirectory
    isUntracked: false
    isMissing: false
  - name: settings
    type: subdirectory
    isUntracked: false
    isMissing: false
  - name: missing_file.txt
    type: content
    tags:
      - test
    hash: ''
    references: []
    comments: ''
    isUntracked: false
    isMissing: false
